[tox]
env_list =
    py{310,311,312,313}-{linux,macos,windows}
    pypy{310}-{linux,macos,windows}

[testenv]
usedevelop = False
download = True

deps =
    pytest>=9.0.2,<10.0.0

# Windows can't update the pip version with pip running, so use Python
# to install things.
install_command = python -m pip install -I {opts} {packages}

passenv = *
setenv =
    # Disable CPython's color output
    PYTHON_COLORS=0
    TOXINIDIR = {toxinidir}

commands =
    python -m pytest tests/ --verbose

[testenv:coverage]
usedevelop = False
download = True

deps =
    pytest>=9.0.2,<10.0.0
    pytest-cov

install_command = python -m pip install -I {opts} {packages}

passenv = *
setenv =
    PYTHON_COLORS=0
    TOXINIDIR = {toxinidir}

commands =
    python -m pytest tests/ --cov=strictyamlx --cov-report=xml --cov-report=term-missing